### ISSUE TITLE
Allow to hide 0 references

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#1]
I think it would be nice to allow to hide 0 reference. I think it would also make a good default to only show the reference is there is one.

![selection_250](https://user-images.githubusercontent.com/139910/37779982-0244183c-2dee-11e8-902b-b4d866aa036c.png)

**Comment by angelozerr** [comment]
Indeed it should be very cool if we could customize that, but today CodeMining API doesn't support this feature: 

`don't draw the line header annotation according the result of mining resolved (in this case "0 reference").` 

It's a very interesting usecase, I will see if it's easy to implement it.

Thanks for your very cool idea!

**Comment by angelozerr** [comment]
@vogella to fix this issue easily, I need https://git.eclipse.org/r/#/c/120005/

**Comment by angelozerr** [comment]
By waiting accept of https://git.eclipse.org/r/#/c/120005/ have you an idea about UI Preferences?

An idea is to have this UI

`[x] Show references [x] only when there are several references`

An idea are welcome!

**Comment by vogella** [comment]
I suggest for the second text : only if there is at least one reference

Am 22.03.2018 19:39 schrieb "Angelo" <notifications@github.com>:

**Comment by vogella** [comment]
Serveral would be wrong as it should also show if there is one

Am 22.03.2018 20:19 schrieb "Lars Vogel" <lars.vogel@vogella.com>:

**Comment by angelozerr** [comment]
@vogella here the UI result:

![image](https://user-images.githubusercontent.com/1932211/37804503-dfe8c070-2e34-11e8-8c85-6def43aa96f5.png)

If you click on =Only if there is at least one reference`, you will see `no command`. Once https://git.eclipse.org/r/#/c/120005/  will be accepted it should work.

**Comment by vogella** [comment]
Yes

Angelo <notifications@github.com> schrieb am So., 15. Apr. 2018, 01:22:

**Comment by angelozerr** [comment]
Thanks @vogella for your feedback. I close this issue.
