### ISSUE TITLE
Hard to click Run and Debug in recent build

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#11]
The mouse pointer seems to react delayed. I need to position the mouse and wait a while before the mouse pointer changes. This is irritating and prevents me from moving and clicking immediately.

![mouse-delayed](https://user-images.githubusercontent.com/139910/38084635-f15f56ca-334d-11e8-9a01-2b305c4fab28.gif)

**Comment by angelozerr** [comment]
There is 2 reasons with this behaviour:

 * performance: the check if mouse over a mining with action is done on SWT mouseHover (which have a delay) and  not on mouseMove
 * if you wish to click quickly on "public" (after Run mining) but you click on "Run", it will execute th emining altough you want just set your cursor on "public".

If you want to change this behaviour, please try it in private class MouseTracker in InlinedAnnotationSupport

Thanks!

**Comment by vogella** [comment]
So this is by design and not a bug? I suggest to close this bug in this case.

**Comment by angelozerr** [comment]
> So this is by design and not a bug? I suggest to close this bug in this case.

It's a choice that I have done for the below 2 reasons, but any change are welcome, if you think it's better to click quickly.

Please create an issue with that in bugzilla or close this issue if you are OK with my choice.

**Comment by vogella** [comment]
After some more testing, it seems that the current behavior is not correctly working. I'm unable to trigger a Run command, see GIF. You see that if I position over "Run" the cursor does not change.

![run-bug](https://user-images.githubusercontent.com/139910/38097296-4e032682-3375-11e8-908d-d5f2cc26e19f.gif)

**Comment by angelozerr** [comment]
Indeed it's a bug, please create a bugzilla issue please and if you have time please help me. Thanks!

**Comment by angelozerr** [comment]
@vogella please retry you last issue. The delay already exists, but there are some improvement about mouse tracks. Thanks for your feedback!

**Comment by angelozerr** [comment]
@vogella I had the same problem than you. It's because of `Only if there is at least one reference` which doesn't draw the mining  and the click doesn't work on this case when mining is not drawn. I will create a bug for that in Platform Text.

**Comment by vogella** [comment]
Still the case with latest I-Build from yesterday. I cannot click on Run.

**Comment by angelozerr** [comment]
Are you using last jdt-codemining? Please do a video. Thanks!

**Comment by vogella** [comment]
![run-not-woring](https://user-images.githubusercontent.com/139910/39626715-6c6d3d52-4fa3-11e8-96dc-30f250a70098.gif)

Yes I updated to the latest code mining.

**Comment by angelozerr** [comment]
And if you test with your TestMaintest2?

**Comment by vogella** [comment]
> And if you test with your TestMaintest2?

Same

**Comment by angelozerr** [comment]
If you remove `Only if there is at least one reference` preference, close your editor and reopen it. Is it working?

**Comment by angelozerr** [comment]
Could you debug mouseMove methof from InlinedAnnotationSupport please. Thanks!

**Comment by vogella** [comment]
Works fine for me in recent build.
