### ISSUE TITLE
No update after preference change

### ISSUE THREAD

**Issue by kthoms** [angelozerr/jdt-codemining#12]
When preferences are changed the minings are not updated, only when the text is reconciled again.

Steps to reproduce: 
- Open a Java file
- Open Code Mining preferences
- Enable or disable something
- Press Apply
=> Expected: The minings appear or disappear

**Comment by angelozerr** [comment]
@kthoms this feature should work with last build of JDT, no?

**Comment by kthoms** [comment]
I'm using JDT 3.14.0.v20180412, that's quite new.

**Comment by angelozerr** [comment]
That's very strange, it should work. It works for other people (like Martin Lippert who have MacOS)?

**Comment by angelozerr** [comment]
Perhaps your problem is because of https://bugs.eclipse.org/bugs/show_bug.cgi?id=533511 ?

**Comment by angelozerr** [comment]
This bug occurs now since https://github.com/angelozerr/jdt-codemining/issues/18

**Comment by angelozerr** [comment]
@kthoms @vogella please reinstall JDT CoodeMining once https://opensagres.ci.cloudbees.com/job/jdt-codemining/42/ will be finished and tell me if it works.

**Comment by angelozerr** [comment]
It should work, if you have problems, please reopen it.
