### ISSUE TITLE
Line numbering and collapse/expand aligned with code lines 

### ISSUE THREAD

**Issue by psuzzi** [angelozerr/jdt-codemining#13]
It would be nice to have line numbers and collapse/expand icons aligned with the "real code", so the user can immediately understand where is "real code", and where is "meta-information" looking at the ruler on the left side.

Currently, the line number and the collapse/expand icon are vertically aligned in the middle of the area contanining both code and meta-annotation. 

![image](https://user-images.githubusercontent.com/352831/38766108-b724bfae-3fcd-11e8-8f70-368d380b4d1b.png)

**Comment by angelozerr** [comment]
I'm afraid it's not an easy task. Please create an issue at bugzilla and add me and @mickaelistria in the bug. Thanks!

**Comment by angelozerr** [comment]
Fixed with https://bugs.eclipse.org/bugs/show_bug.cgi?id=534314
