### ISSUE TITLE
Annotation misplacement/overlapping with MacOS.

### ISSUE THREAD

**Issue by psuzzi** [angelozerr/jdt-codemining#14]
When I startup Eclipse, or after setting the preferences to enable codemining, I see strange overlappings in the text, as you can see in the left of the attached image. The issue is fixed after clicking on the TextArea. (I obseved this behavior on Mac)

Is this something we should fix on jdt.codemining or in eclipse.text ?

![image](https://user-images.githubusercontent.com/352831/38768002-c59104f2-3fec-11e8-8ffe-8275594e7666.png)

**Comment by angelozerr** [comment]
@psuzzi inlined annotation seems not workinh with MacOS. Is it a problem with TextLayout of MacOS? It exists a bug with this problem https://bugs.eclipse.org/bugs/show_bug.cgi?id=532924

If you can help us with that, any help are welcome! I have not MacOS, so I cannot study the problem -(

**Comment by angelozerr** [comment]
@psuzzi please retry with platform master. Thanks!

**Comment by angelozerr** [comment]
This issue should be fixed now. If you have problem please reopen it.
