### ISSUE TITLE
Weird Editor behaviors: random split editor and NPE when splitting the editor  

### ISSUE THREAD

**Issue by psuzzi** [angelozerr/jdt-codemining#15]
I captured this screenshot during a debug session. Without executing any particular command, the editor split in two. I was just in the middle of a debug session, and I edited the code under debug. 
(The below screenshot is not what happens when you open a split editor)

![image](https://user-images.githubusercontent.com/352831/38772291-49037a54-4033-11e8-8e95-8924cf3c08f8.png)

On the opposite, this screenshot shows what happens when you open a split editor. The split editor seems not working. (tested via Window > Editor > Vertical Split Editor)

![image](https://user-images.githubusercontent.com/352831/38772294-532b8dfa-4033-11e8-84d4-610d5412ad67.png)

Attached, you can see the stack trace for the reproducible issue: when you open a split editor. 

[split-editor-stack-trace.txt](https://github.com/angelozerr/jdt-codemining/files/1911028/split-editor-stack-trace.txt)

**Comment by angelozerr** [comment]
Could you retry by using Platform from master please and tell me if it fixes your issue. Thanks!

**Comment by angelozerr** [comment]
@psuzzi I close this issue. If yiu have again problem, please reopen it. Thanks!
