### ISSUE TITLE
Feature request: Draw opening statement for brackets

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#16]
IMHO it would be really nice to have the option to draw the opening statement of closing curley brackets:

For example:
```java
if (parent != null) {
//lots of code here
} (-> draw this via code mining) //if (parent != null) {
```

**Comment by angelozerr** [comment]
Indeed, very good idea!

**Comment by angelozerr** [comment]
@vogella once https://opensagres.ci.cloudbees.com/job/jdt-codemining/21/ will be finished, please reinstall jdt-codemining.

I have implemented your idea very quickly and it works only with if statement. Here the result:

![image](https://user-images.githubusercontent.com/1932211/38945802-cf0113bc-4337-11e8-8ed3-b9ee520a4f57.png)

Hope you will like it. Any feedback are welcome, thanks!

**Comment by vogella** [comment]
Looks cool. Thanks. Maybe you could add: "from line number xxx" and a click
listener which jumps to the line if you click on it? Would be very helpful
IMHO

Angelo <notifications@github.com> schrieb am Mi., 18. Apr. 2018, 18:39:

**Comment by angelozerr** [comment]
@Lars once https://bugs.eclipse.org/bugs/show_bug.cgi?id=533811 will be merged. You must activate `Show end statement` preferences:

![image](https://user-images.githubusercontent.com/1932211/39004200-0b331d24-43fd-11e8-8787-2463e94ebda4.png)

and you will benefit with end statement mining:

 * draw begin of statement at the end of statement as mining
 * click on mining jumps to begin of statement.

Here a demo:

![codeminingendstatementdemo](https://user-images.githubusercontent.com/1932211/39004267-3b94b70c-43fd-11e8-8cf1-fdb46d1b5a2e.gif)

**Comment by angelozerr** [comment]
@vogella can we close this issue? Have you some other requirements?

Please note that you must use platform.text from master  https://bugs.eclipse.org/bugs/show_bug.cgi?id=533811 to benefit with the fix on click on mining.

**Comment by vogella** [comment]
Looks great except the bug I reported in https://bugs.eclipse.org/bugs/show_bug.cgi?id=534156 which adds some special sign.

![selection_332](https://user-images.githubusercontent.com/139910/39369770-791203e6-4a3d-11e8-9520-d179f207e9b9.png)

Maybe you are using a platform specific line delimitor so something else?

In general, it would be nice to have this for all brackets if they are x line apart. For example, I don't need the info for single line if statements but for if statements more then x (based on customization) it would be drawn. 2 lines would be a good default IMHO.

**Comment by angelozerr** [comment]
> In general, it would be nice to have this for all brackets if they are x line apart. 

Done with new preferences:

![image](https://user-images.githubusercontent.com/1932211/39499737-34174d34-4db0-11e8-962f-40e235bdcb19.png)

Please give me feedback (when minimum line number is a good label? 20 is a good default value?) Thanks!

**Comment by vogella** [comment]
Looks good to me. Not sure about a good default.  I personally will set it to 4, I think.

I think this one can be closed.

**Comment by angelozerr** [comment]
>  I personally will set it to 4, I think.

I can do that if you wish.

**Comment by vogella** [comment]
> I can do that if you wish.
I have no strong opinion here, so only change it, if you think that is useful. I think using 20 may make this feature not very visible, so using 4 may promote it. User can always adjust if he discover this features.

**Comment by angelozerr** [comment]
Ok now it's 4.

**Comment by vogella** [comment]
Thanks
