### ISSUE TITLE
Show variable values inline while debugging

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/jdt-codemining#17]
Show variable values inline while debugging. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=507546

@vogella I'm working on this issue and it starts working, but there is again several bugs. Please play with it and give me feedback. Thanks!

**Comment by vogella** [comment]
Great stuff Angelo. Could you enable it also for normal debugging?

**Comment by angelozerr** [comment]
> Great stuff Angelo. Could you enable it also for normal debugging? My normal scenario is to debug regular code, I debug unit tests with less frequency.

My code works with any Java debugging. Please try and tell me if it works for you. To benefit with this mining, ypu must enable `Show variable values inline while debugging` from the `Code Mining` prefernces page.

**Comment by angelozerr** [comment]
Here a new demo:

![inlineddebuggingdemo](https://user-images.githubusercontent.com/1932211/39230995-e1a0683e-4868-11e8-8a05-52cce59f6c6f.gif)

**Comment by vogella** [comment]
I don't see the 'Show variable values inline while debugging' option. Did
you update the update side?

Angelo <notifications@github.com> schrieb am Mi., 25. Apr. 2018, 09:13:

**Comment by vogella** [comment]
Great feature, thank you for that.

I found a bug, I think. In the attached screenshot it only draws the value for the declaration but not for the usage as method parameters.

See the second line in the test? This should show "application" like in the line before.

![selection_332](https://user-images.githubusercontent.com/139910/39369390-73eceaa8-4a3c-11e8-838b-9bd905353fbc.png)

**Comment by angelozerr** [comment]
@vogella to be honnest with you, I have do that quickly and show debug value just for variable declaration.

I'm sorry, I don't understand your requirement, could you post a new screenshot with the waited result please. Thanks!

**Comment by vogella** [comment]
> I don't understand your requirement
See https://www.jetbrains.com/help/idea/2016.2/inline-debugging.html
During debugging the values of variables should be shown in very line, e.g.,:

int i=15;
(200 lines later)
callSomething(i) -> I like to see the value of the variable here

**Comment by rgra** [comment]
With a bigger font size the placing is a little off:
![grafik](https://user-images.githubusercontent.com/1619079/39395664-5cd6b038-4ae1-11e8-8c28-7c0348ddcaf7.png)

Text Font: Consolas 20
OS: Windows 10
Latest JDT and Mining versions as of today.

And: Thank you so much for implementing those code mining features. They will help a lot in daily business!

**Comment by angelozerr** [comment]
> callSomething(i) -> I like to see the value of the variable here

@vogella once https://opensagres.ci.cloudbees.com/job/jdt-codemining/33/ will be finished, please reinstall JDT CodeMining. I have improved too the location of mining which is displayed at the end of the line (after `;` for instance).

![image](https://user-images.githubusercontent.com/1932211/39422894-b9bea06e-4c6f-11e8-994b-4884d141c852.png)

**Comment by rgra** [comment]
Do you plan on having a option to show old variable values when a variable is reassigned? For += etc this would be useful. 
Would also be nice to use detail formatted instead of toString.

**Comment by angelozerr** [comment]
> Do you plan on having a option to show old variable values when a variable is reassigned? For += etc this would be useful.

I don't know if it's possible with debugger stack frame info.

> Would also be nice to use detail formatted instead of toString.

I'm using the same code than debugger when you do an hover with DebugElementHelper.getLabel(variable). I don't know if it's an easy task to add more detail.

@rgra I close this issue, if you need some new feature, please create an issue per feature by adding sample and give more info please. Thanks!
