### ISSUE TITLE
Improve preferences to categorize codemining

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/jdt-codemining#18]
Here the current result:

![image](https://user-images.githubusercontent.com/1932211/39318562-c3505eb8-497e-11e8-818f-222464286517.png)

@vogella please give me feedback. Thanks!

**Comment by vogella** [comment]
Looks great. Thanks.

**Comment by angelozerr** [comment]
@vogella I close this issue, please reopen it or create a new issue if you need some improvement. Thanks!
