### ISSUE TITLE
Please add junit 5 support in code mining

### ISSUE THREAD

**Issue by Ravisankar-Challa** [angelozerr/jdt-codemining#20]
Junit Jupiter(Junit 5) @Test annotation is moved to a new package org.junit.jupiter.api.Test. Code mining should be able to handle new Junit 5 @Test annotation

**Comment by angelozerr** [comment]
Please see https://bugs.eclipse.org/bugs/show_bug.cgi?id=531779

**Comment by angelozerr** [comment]
@Ravisankar-Challa once https://opensagres.ci.cloudbees.com/job/jdt-codemining/37/ job will be finished, please reinstall JDT CodeMining and tell me if it works for you. Thanks!

**Comment by Ravisankar-Challa** [comment]
Looks like the Access Specifier for junit test should be public for code mining to show Run|Debug options.

Junit 5 allows to write unit tests with out access specifier.

![junit5](https://user-images.githubusercontent.com/11788842/39669884-a3bf5a62-513b-11e8-97bf-10b09eeb2d17.png)

**Comment by angelozerr** [comment]
@Ravisankar-Challa thanks for your feedback. To be honnest with you I don't know JUnit5. It should be very cool if you could create an issue per JUnit5 request please. Thanks!

**Comment by angelozerr** [comment]
I close this issue for https://github.com/angelozerr/jdt-codemining/issues/24
