### ISSUE TITLE
Editor not updated after changing the preferences

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#23]
I had an editor open and activated the preferences.

![preferences _336](https://user-images.githubusercontent.com/139910/39626310-a68df4b0-4fa1-11e8-8f1e-5f9697c7f147.png)

After apply and close the code minining annotations are not shown.

![selection_337](https://user-images.githubusercontent.com/139910/39626337-bcb20aec-4fa1-11e8-84c4-3a037aa42457.png)

If I close and reopen the editor they are shown.

I would expect to see them after I press "Apply and Close" in the preferences.

![selection_338](https://user-images.githubusercontent.com/139910/39626372-eafe101c-4fa1-11e8-99c3-227d13dec7a3.png)

**Comment by angelozerr** [comment]
Yes I know @vogella I close this issue because it's the same problem than https://github.com/angelozerr/jdt-codemining/issues/12
