### ISSUE TITLE
Please add support for junit 5 test methods with no access modifier 

### ISSUE THREAD

**Issue by Ravisankar-Challa** [angelozerr/jdt-codemining#24]
Junit Jupiter (Junit 5) supports methods with out access modifier or default access modifier scope (same package).

looks like the Access Specifier for junit 5 test should be public for code mining to show Run|Debug options.

Working:
![working](https://user-images.githubusercontent.com/11788842/39670038-e7b52af0-513e-11e8-9beb-f0bc3be69edc.png)

Not Wortking:
![notworking](https://user-images.githubusercontent.com/11788842/39670039-efa951f0-513e-11e8-93a5-0a2f77cccdde.png)

Junit 5 allows to write unit tests with out access specifier.

![junit5](https://user-images.githubusercontent.com/11788842/39669884-a3bf5a62-513b-11e8-97bf-10b09eeb2d17.png)

**Comment by angelozerr** [comment]
@Ravisankar-Challa once https://opensagres.ci.cloudbees.com/job/jdt-codemining/47 will be finished, please reinstall jdt codemining an dtell me if it's ok for you. Thanks!

**Comment by Ravisankar-Challa** [comment]
It's working.
![image](https://user-images.githubusercontent.com/11788842/39962452-29485b06-5692-11e8-8d40-daefaaccb0a5.png)

**Comment by angelozerr** [comment]
Cool, thanks for your feedback.
