### ISSUE TITLE
Show Git avatar before @author as mining for Java method and class

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/jdt-codemining#25]

**Comment by angelozerr** [comment]
@vogella after a quick implementation, here the result:

![image](https://user-images.githubusercontent.com/1932211/39803749-45f660cc-5372-11e8-9de4-2307fc969586.png)

Do you think it's interesting or not? If you like it , I will commit my work.

**Comment by vogella** [comment]
Yes, Looks cool. Maybe contribute it to Egit?

Angelo <notifications@github.com> schrieb am Mi., 9. Mai 2018, 10:18:

**Comment by angelozerr** [comment]
> Yes, Looks cool. Maybe contribute it to Egit?

I have copied/pasted some code from https://github.com/eclipse/egit-github/tree/master/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui

Here the preferences to show avatar:

![image](https://user-images.githubusercontent.com/1932211/39955302-e12b7fda-55cc-11e8-8887-f915a50e6bb8.png)

Please give me feedback, thanks!
