### ISSUE TITLE
No parameter names and types information for Constructor calls

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#28]
It would be great if I could also see the names and types for constructor calls:

````
GridData gridData = new GridData(SWT.NONE, SWT.FILL, true, true);	
````

![image](https://user-images.githubusercontent.com/139910/40054512-5ee7fbcc-5845-11e8-9085-c8985775a20a.png)

**Comment by angelozerr** [comment]
Yes sure, do you think we should add a preference for that?

**Comment by vogella** [comment]
I would think everyone wants to see the same info for method and constructor calls, so IMHO a extra preference is not necessary.

**Comment by angelozerr** [comment]
Done:

![image](https://user-images.githubusercontent.com/1932211/40111390-fb3b5a88-5902-11e8-9a79-b0c56808b866.png)

**Comment by vogella** [comment]
Very cool.

**Comment by vogella** [comment]
Does you build update the update site automatically after a while?

**Comment by angelozerr** [comment]
Yes, please wait for doen of job https://opensagres.ci.cloudbees.com/job/jdt-codemining/53/
