### ISSUE TITLE
Show end statement does not react to preference changes

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#31]
Using latest and greatest code mininig I still have to close the editor to see the end brackets 
JDT CodeMining	1.0.0.201805161036	jdt-codemining-feature.feature.group	Angelo ZERR

Example editor after activating the setting.

![selection_351](https://user-images.githubusercontent.com/139910/40116785-0a1e2460-5915-11e8-90b5-6382a0269108.png)

If I close and re-open I see the code mininig

![selection_352](https://user-images.githubusercontent.com/139910/40116829-3a1169c0-5915-11e8-8209-d5f1847b1ac9.png)

**Comment by angelozerr** [comment]
That's strange, it works for me? Have you the same problem with other minings?

**Comment by angelozerr** [comment]
Have you the problem again?

**Comment by vogella** [comment]
Works fine with latest and greatest. Thanks, Angelo.
