### ISSUE TITLE
Git code mining for methods

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#33]
I'm not 100 % sure here but I think the code mining annotations should show the last changed date of the whole method and the last changer. AFAICS it currently shows the author and date of the change for the method signature which is less useful to me.

![git-code-mining](https://user-images.githubusercontent.com/139910/40414609-fab2884a-5e78-11e8-9576-7ce5a2669e3b.png)

**Comment by angelozerr** [comment]
@vogella oncehttps://opensagres.ci.cloudbees.com/job/jdt-codemining/55/ will be finished, please reinstall it and tell me if it works for you. Thanks!

**Comment by vogella** [comment]
Cool. Thanks a bunch.

**Comment by vogella** [comment]
Works fine for me.
