### ISSUE TITLE
Use a bit more spacing in Debugging

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#34]
![selection_362](https://user-images.githubusercontent.com/139910/40424619-60f87ad4-5e96-11e8-954e-b862c5d51669.png)

I think a bit more empty space before the debugging info would be helpful. Compare currently Eclipse with IntelliJ and IntelliJ looks better.

https://www.jetbrains.com/help/idea/inline-debugging.html

**Comment by angelozerr** [comment]
@vogella once https://opensagres.ci.cloudbees.com/job/jdt-codemining/56/ will be finished please reinstall and tell me if it's OK for you. Thanks!

**Comment by angelozerr** [comment]
@vogella is it working for you?

**Comment by angelozerr** [comment]
It should work, if you have problem please reopen it.
