### ISSUE TITLE
Show run/debug mining for main method

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/jdt-codemining#36]
Show run/debug mining for main method

**Comment by angelozerr** [comment]
@vogella here the result:

 * preferences:

![image](https://user-images.githubusercontent.com/1932211/40453521-bf67b87e-5ee5-11e8-8403-a4c2a9cb91f2.png)

 * mining result:

![image](https://user-images.githubusercontent.com/1932211/40453598-056c11bc-5ee6-11e8-8b21-d70b1fa4b8a3.png)

Any feedback are welcome, thanks!

**Comment by vogella** [comment]
Definitely a cool thing. Thanks a bunch.

**Comment by angelozerr** [comment]
Cool! Glad it please you:)
