### ISSUE TITLE
Varargs not shown

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#38]
During the fix of Bug 533156, I noticed that the type for varargs is shown as array.

![image](https://user-images.githubusercontent.com/139910/41220937-11929624-6d63-11e8-8764-c7efce2f9c03.png)

**Comment by angelozerr** [comment]
Please retry to install JDT CofeMining and tell me if it's OK for you. Thanks!

**Comment by angelozerr** [comment]
@vogella can I close this issue?

**Comment by vogella** [comment]
Works fine now. Thanks.
