### ISSUE TITLE
Class with unit tests should also have a Run command to run all Junit tests

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#4]
See Screenshot, no Run for the class.

![selection_257](https://user-images.githubusercontent.com/139910/37827769-1aef61d8-2e99-11e8-9538-daf5fa66f7f4.png)

**Comment by angelozerr** [comment]
Indeed, the JUnit support is very basic for the moment, it work sonly with method and works only with @Test annotation or @org.junit.test.Test

See issues:

 * https://bugs.eclipse.org/bugs/show_bug.cgi?id=529316
 * https://bugs.eclipse.org/bugs/show_bug.cgi?id=531779

Do you think we could work together about this topic?

**Comment by vogella** [comment]
> Do you think we could work together about this topic?

I'm definitely will to help but I'm not  a JDT committer AND your development skills are way above my development skills. :-) But I'm happy to help with testing.

**Comment by angelozerr** [comment]
> I'm definitely will to help but I'm not a JDT committer 

JDT CodeMining will not be in part of Photon. See 4.9 target at https://bugs.eclipse.org/bugs/show_bug.cgi?id=529127

So my idea is to work on jdt-codemining and add the more features (thanks to create issues!) and when 4.9 will be ready, I could create gerrit patch for JDT with jdt-codemining. So don't hesitate to create issues, it requires improve of codemining and I would like to do that before Photon release.

> AND your development skills are way above my development skills. :-)

You are so wrong!

> But I'm happy to help with testing.

Thanks!

**Comment by vogella** [comment]
>JDT CodeMining will not be in part of Photon. See 4.9 target at https://bugs.eclipse.org/bugs/show_bug.cgi?id=529127

Let's see, these things might change.

**Comment by angelozerr** [comment]
Done:

![image](https://user-images.githubusercontent.com/1932211/40112217-91202ad6-5905-11e8-9170-2d3cc8464783.png)
