### ISSUE TITLE
Java code mining not available in class file

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#41]
If I only activate code mining for debugging they are not shown.

![image](https://user-images.githubusercontent.com/139910/41343885-0c94e6b0-6f00-11e8-926d-e74711114327.png)

**Comment by vogella** [comment]
I also restarted the debugging session, still I do not see the debug information.

**Comment by angelozerr** [comment]
I cannot reproduce your problem -(

**Comment by vogella** [comment]
Looks like the display of the debug information is not visible for class files which I debug. See new screenshot.

@angelozerr to reproduce put a breakpoint for example into Control (assuming you do not have the SWT plug-ins imported into your workspace) and try to see the debug information.

![image](https://user-images.githubusercontent.com/139910/41713824-9acd88e8-754e-11e8-88c1-d5fa5e316d46.png)

**Comment by angelozerr** [comment]
Ok I I understand your use case, you are in `class file` and not in `java file`. Have you the problem with  `java file`?

**Comment by vogella** [comment]
> Have you the problem with java file
Not that I noticed so far.

> Is other minings works with class file?
Now that you say it, no, non are working.

**Comment by angelozerr** [comment]
@Lars your problem is about class file and not with debug code mining. It will change a lot of thing since IJavaElement cannot returns well offset with class file. In other words we need to work only with AST and not with IJavaElement.

There is a same problem with https://github.com/angelozerr/jdt-codemining/issues/37

**Comment by angelozerr** [comment]
Once https://opensagres.ci.cloudbees.com/job/jdt-codemining/65/ will be finished, please reinstall and tell me if it works. Thanks @vogella !

**Comment by angelozerr** [comment]
@voggela is it working for you?

**Comment by angelozerr** [comment]
@vogella is it working for you?

**Comment by vogella** [comment]
Yes, thanks a bunch
