### ISSUE TITLE
Fails to install on Eclipse 4.9

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#44]
Error: 
Cannot complete the install because one or more required items could not be found.
  Software being installed: JDT CodeMining 1.0.0.201806221018 (jdt-codemining-feature.feature.group 1.0.0.201806221018)
  Missing requirement: Egit CodeMining 1.0.0.201806221018 (org.eclipse.egit.codemining 1.0.0.201806221018) requires 'osgi.bundle; org.eclipse.egit.core 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: JDT CodeMining 1.0.0.201806221018 (jdt-codemining-feature.feature.group 1.0.0.201806221018)
    To: org.eclipse.equinox.p2.iu; org.eclipse.egit.codemining [1.0.0.201806221018,1.0.0.201806221018]

**Comment by vogella** [comment]
Silly me, sorry.

**Comment by angelozerr** [comment]
Could you tell me what was your problem?

**Comment by vogella** [comment]
Egit was not installed.
