### ISSUE TITLE
Debug-Mining using ".toString()" result

### ISSUE THREAD

**Issue by chhorz** [angelozerr/jdt-codemining#54]
First of all i like the plugin a lot and you did a great job.

Maybe the debug mining could be improved if the mining would show the result of the `.toString()` method and not the type and id.

![debug-mining](https://user-images.githubusercontent.com/16685526/42269878-aede51b0-7f7f-11e8-9667-e9b3dbe061df.png)

Regards
Christian

**Comment by felipebn** [comment]
Hi everyone!

After looking the code and not finding exactly where the value was resolved I remembered that you can configure how Eclipse displays the variable value for Variables views.

Go to **Preferences > Java > Debug > Detail Formatters**. On the section *Show variable details ('toString()' value)* select *As the label for all variables*.

The result looks like this:

![debug](https://user-images.githubusercontent.com/209101/42345842-956bbba4-8098-11e8-82cd-ce7acbf9877a.png)

So I think @angelozerr can close this issue.

PS: @angelozerr Thanks for this plugin!! It was the only thing from IJ that I wanted to have on Eclipse.

**Comment by angelozerr** [comment]
@chhorz thank a lot for your feedback! To be honnest with you I didn't know this feature:)

The magic line code which display that is https://github.com/angelozerr/jdt-codemining/blob/master/org.eclipse.jdt.codemining/src/org/eclipse/jdt/internal/ui/javaeditor/codemining/debug/InlinedDebugCodeMining.java#L81

```java
org.eclipse.debug.internal.ui.views.launch.DebugElementHelper.getLabel(variable)
```
