### ISSUE TITLE
Don't show default parameter names ("arg0")

### ISSUE THREAD

**Issue by enikao** [angelozerr/jdt-codemining#55]
If we don't know the parameter name (e.g. because of missing sources), they should not be shown.

![codemining](https://user-images.githubusercontent.com/2211690/42271564-f09b4b54-7f83-11e8-922c-1323ec736381.png)

**Comment by angelozerr** [comment]
@vogella what do you think about that? If you like it, do we need a preference for that?

**Comment by enikao** [comment]
Rationale: It doesn't add information, but takes space and clutters the view.

**Comment by angelozerr** [comment]
@enikao I have started to implement this feature, but I would like to know if need a preferences for that?

**Comment by gliviu** [comment]
I wouldn't add any preference. I see no use case where unknown args are needed.

**Comment by enikao** [comment]
I agree with @gliviu, a preference doesn't make sense.
