### ISSUE TITLE
Show method parameter names with Lombok causes unwanted behaviour

### ISSUE THREAD

**Issue by koell09** [angelozerr/jdt-codemining#58]
If "Show method parameter names" is enabled and the application uses Lombok annotations (e.g. `@Data`), then the code mining hint is unwanted IMHO:

![unwantedlombok](https://user-images.githubusercontent.com/40605543/42274379-bd8ea752-7f8c-11e8-99ec-c7a0d44e5292.PNG)

The information there is not necessary and should be removed for improved readability.

**Comment by angelozerr** [comment]
Same issue than https://github.com/angelozerr/jdt-codemining/issues/37#issuecomment-399357306 

As I would like to move JDT CodeMining to JDT, I will not support Lombok (which is a special case).

Those information that you see is about Lombok which update with Java agent the JDT ASTNode. I have tried to support it but it was a nightmare, so I have gaven up to spend my time to improve other feature of JDT CodeMining. 

Anyway any PR are welcome!
