### ISSUE TITLE
Debugging Output - Show actual values of Objects instead of type

### ISSUE THREAD

**Issue by mscholzj** [angelozerr/jdt-codemining#62]
thank you for your work on this project.

Currently the debugging output shows only the object type instead of the actual value or the toString() value. That makes it almost useless for me as i have a lot of non-primitive types aka Objects.

This is my current test case. The primitives are shown correctly. 

![auswahl_999 080](https://user-images.githubusercontent.com/5197206/42376573-e325b8d6-811f-11e8-8086-fa23857d6c19.jpg)

Should the debugging output call the toString() of objects?

Could it use the eclipse Detail Formatter one can create in the 'Variables' view?

----
CodeMining = 1.0.0.201807051153
OS = Linux 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Window = MATE Desktop Environment 1.8.1
Eclipse = Eclipse IDE for Java Developers Version: Photon Release (4.8.0) Build id: 20180619-1200

**Comment by angelozerr** [comment]
Same issue than https://github.com/angelozerr/jdt-codemining/issues/54

**Comment by mscholzj** [comment]
Thanks. I think a hint in the readme might help other users.

**Comment by angelozerr** [comment]
Good idea, could you do a PR for that?
