### ISSUE TITLE
Publish on marketplace

### ISSUE THREAD

**Issue by paulvi** [angelozerr/jdt-codemining#64]
Please publish on marketplace

**Comment by angelozerr** [comment]
I hesitate to do that because:

 * JDT Code Mining is not mature yet
 * I hope JDT Code Mining will move to JDT project

**Comment by paulvi** [comment]
Publish as Alpha

When it is within JDT, disable by removing update site URL

I can do that. Takes half an hour

**Comment by angelozerr** [comment]
> I can do that. Takes half an hour

Indeed it's easy, but it requires that I must manage some release of JDT CodeMining. I don't know when I will have a  stable plugin.

**Comment by angelozerr** [comment]
@paulvi I close this issue because I will start to contribute to JDT. See https://github.com/angelozerr/jdt-codemining/issues/66
