### ISSUE TITLE
Print margin is not drawn continuously. 

### ISSUE THREAD

**Issue by gayanper** [angelozerr/jdt-codemining#69]
When code mining is enabled for Java code (i haven't had the change to test in any other text editor which has in builtin code mining support) the print margin in not continuously drawn. Basically it seems the line render which renders the mining information doesn't draw the margin column on that line.
![image](https://user-images.githubusercontent.com/7471994/44893523-290f9c80-ad09-11e8-9ba5-4b93a39a34e7.png)

This is common in all mining renderings such s Run | Debug.

**Comment by angelozerr** [comment]
Same issue than #59
