### ISSUE TITLE
[Improvement] Support for different syntax color for "End Statements"

### ISSUE THREAD

**Issue by gayanper** [angelozerr/jdt-codemining#71]
Can we add support for rendering the "end statements" in a different color so that it is prominent its not a ordinary comment. Today it uses the same comment syntax color which confuses in some situations where its a comment or a mining instruction.
![image](https://user-images.githubusercontent.com/7471994/45136901-f90e4080-b1c3-11e8-9a51-eadd74aa38e8.png)

**Comment by angelozerr** [comment]
I agree with you, but we need to find a generic mean in Eclipse IDE with UI preferences to change this settings. @mickaelistria have you some idea to customize color, font of codemining?

**Comment by angelozerr** [comment]
I close this bug since https://github.com/angelozerr/jdt-codemining/issues/60 is the same thing
