### ISSUE TITLE
Add support for enabling references only on classes

### ISSUE THREAD

**Issue by gayanper** [angelozerr/jdt-codemining#75]
In Some instances showing references on each method might not be that usefull. So it will be good if we can configure where to show the references on method level as well.
Under in settings:
- Show references
  - Only if there is at least on reference
  - **Only on classes**

**Comment by gayanper** [comment]
If this is a good feature i can look into implementing it 😄

**Comment by angelozerr** [comment]
I think its a Good idea but imho We should have 3 préférences like enable for class méthod and fields in the future

**Comment by angelozerr** [comment]
Yes but for fields is not supported yet

**Comment by gayanper** [comment]
Yes so for now we can have only
- class
- method

I will try to send a screenshot after i do some changes so you could see if it done correctly.

**Comment by gayanper** [comment]
How does this looks like ? 
![image](https://user-images.githubusercontent.com/7471994/46363262-239ecc80-c690-11e8-9fa5-51997ce33566.png)

**Comment by angelozerr** [comment]
Perhaps remove the "Show" and have "On classes", no?

**Comment by angelozerr** [comment]
Yes it was my idea, do you like it too?

**Comment by gayanper** [comment]
Yes i think that's go idea

**Comment by gayanper** [comment]
@angelozerr when will this issue be released ?

**Comment by angelozerr** [comment]
There were a buld problem. Now it should be fixed. The idea is that on each commit, update site is done. You can follow jobs at https://opensagres.ci.cloudbees.com/job/jdt-codemining/

**Comment by gayanper** [comment]
Thanks got the changes with he latest build.
