### ISSUE TITLE
Change variable name creates temporary wrong drawing

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#8]
See animated Gif.

![peek-wrong-drawing](https://user-images.githubusercontent.com/139910/37829119-160a4d7c-2e9e-11e8-8c40-726e72c2cae9.gif)

**Comment by angelozerr** [comment]
Sorry @vogella I don't understand the problem?

**Comment by vogella** [comment]
![peek4](https://user-images.githubusercontent.com/139910/37829875-05b567e2-2ea1-11e8-9cbd-a75f83b61bc6.gif)

The new give shows this correct (sorry, I rarely work with animated gifs). You see the additional info jumping from left to right.

**Comment by vogella** [comment]
As you hopefully can see the "filename:" moves from left to right during me typing.

**Comment by vogella** [comment]
I also see it in other places. For example type: ContextInjectionFactory.make(String.class); Now select String and type "Integer". It again jumps from left to right. IMHO it should stay left.

**Comment by angelozerr** [comment]
Indeed I know this behaviour and I don't like it, but I don't know for the moment how to fix that -( Please create an new issue to bugzilla please.

**Comment by vogella** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532835

**Comment by angelozerr** [comment]
@vogella I have studied the problem and I'm afraid that there is no solution for that.  Problem comes from AST vistor in the line https://github.com/angelozerr/jdt-codemining/blob/master/org.eclipse.jdt.codemining/src/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java#L36

When you remove `newFile` parameter, the line code 

```java
public boolean visit(MethodInvocation node) {
		List arguments= node.arguments();
```

contains 1 argument node and not 2, so there is one mining and not 2 minings. I don't know how to fix that -(

**Comment by vogella** [comment]
Maybe you could delay the drawing for a while so that the update does not
happen? In my example I pasted the new method name. So a delayed update of
for example 200 milliseconds would not show the "wrong" drawing.

Angelo <notifications@github.com> schrieb am Di., 27. März 2018, 18:24:

**Comment by angelozerr** [comment]
> Maybe you could delay the drawing for a while  

We cannot manage this delay. The idea is to execute the codemining updater when ICompilationUnit is ready.

**Comment by angelozerr** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=535899

**Comment by angelozerr** [comment]
@vogella since https://bugs.eclipse.org/bugs/show_bug.cgi?id=535899 has been fixed, could you tell me if it improve your issue and if we can close this issue? Thanks!

**Comment by vogella** [comment]
I think this has been fixed. Thanks @angelozerr
