### ISSUE TITLE
Clarify situation of Plugin with Eclipse 4.10

### ISSUE THREAD

**Issue by FrzMe** [angelozerr/jdt-codemining#95]
It seems like show references and show implementations made it into Eclipse 4.10, the other features are still missing, is it possible to get them back by installing the plug-in in Eclipse 4.10?

**Comment by angelozerr** [comment]
Have you Enabled Code Mining from the JDT preferences page of 4.10?

**Comment by FrzMe** [comment]
Am I missing something? I see the preference page Code Minings (it looks the same as displayed here https://www.eclipse.org/eclipse/news/4.10/images/jdt-codemining-preferences.png 
(via https://www.eclipse.org/eclipse/news/4.10/jdt.php#jdt-codemining ))
It only offers "Show references" and "Show implementations". I understood that this is the results of your work now included in JDT. It however seems that the other Code Minings (Show Method Parameters, Show Variable Values, ...) are not included.
Is it possible to get these additional features by installing the Plugin in Eclipse 4.10 or are there conflicts with the features included in JDT?

**Comment by angelozerr** [comment]
You must select `Enable code minings` from `CodeMining` preferences and after you should be abailable to to use code mining from `Code Mining Experimental` preferences.

**Comment by FrzMe** [comment]
Thanks, works perfectly. :)

**Comment by OlivierJaquemet** [comment]
I had the same confusion regarding the need or not to install the plugin on 4.10.
IMHO it would be nice to provide more information in the main README.md indicating that 

- Eclipse 4.10 provides "basic code mining feature" which are NOT conlictual with JDT-codemining, 
https://www.eclipse.org/eclipse/news/4.10/jdt.php#jdt-codemining
- JDT-codemining provides additional capacities to default 4.10 codemining 
- JDT-codemining can be installed on older Eclipse in which "native" codemining is not yet available 

(if all that is correct... ;) )

**Comment by angelozerr** [comment]
@OlivierJaquemet I agree with you, we need that and `Code Mining Experimental ` should be disabled and have a link to the CodeMining preferences to enable it.

But for the moment I'm very busy and  no time to do that. Today references and implementations code mining are migrated to JDT. I would like to move step by step other minings to JDT. 

The references/implementation sof 4.10 are more advanced than jdt-codemining (you can click on implementations code miningsn etc)

**Comment by OlivierJaquemet** [comment]
Thank you @angelozerr for this feedback. Regarding the UI itself, it is a little confusing at first, but not that problematic (to me). However, not having any information on the jdt-codemining project on whether it is compatible with 4.10 is more of an issue to me. But I completely understand it requires time, something all of us are missing.

English is not my native language, but as an attempt to help a bit, I have submitted this PR if you are interested in adding this information and if it can help you with that : https://github.com/angelozerr/jdt-codemining/pull/96

Happy holidays to all the jdt-codemining team. And thanks for providing great features to our IDE !

**Comment by angelozerr** [comment]
> Happy holidays to all the jdt-codemining team. And thanks for providing great features to our IDE !

Thanks ! And thanks for your PR.
